variables:
  azureSubscription: nepeters-azure
  resourcegroup: tailwind-traders
  location: eastus
  ImageName: website
  containerRegistryName: ttacrajie6a75n2mue
  containerRegistryFqdn: ttacrajie6a75n2mue.azurecr.io
  aks-cluster: tailwindtradersaksajie6a75n2mue
  aks-cluster-rg: tailwind-traders
  ingress: 8e1375690b8947f8adf2.eastus.aksapp.io

stages:

- stage: build
  jobs:
  - job: build

    pool:
      name: Hosted Ubuntu 1604

    steps:

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'ls Source/Services/Tailwind.Traders.Cart.Api'