{{- $name := include "tt-stock.fullname" . -}}


apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "tt-stock.name" . }}
    chart: {{ template "tt-stock.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  APPLICATION_INSIGHTS_IKEY:  "{{ .Values.inf.appinsights.id }}"
  COSMOSDB_AUTHKEY: {{ .Values.inf.db.stock.auth }}
  COSMOSDB_HOST: {{ .Values.inf.db.stock.host }}
  ISSUER: {{ .Values.sec.issuer }}
  SECURITYKEY: {{ .Values.sec.securityKey }}
  
