kind: helm-release
apiVersion: 1.1
build:
  context: ..\..\
  dockerfile: Dockerfile
install:
  chart: ../../../Deploy/helm/mobilebff
  set:
    replicaCount: 1
    image:
      tag: $(tag)
      pullPolicy: Never
    ingress:
      annotations:
        kubernetes.io/ingress.class: traefik-azds
      hosts:
      # This expands to [space.s.]identity.<guid>.<region>.aksapp.io
      - $(spacePrefix)$(rootSpacePrefix)tt$(hostSuffix)
  values:
  - ../../../Deploy/helm/gvalues.azds.yaml
  - values.dev.yaml?
  - secrets.dev.yaml?
configurations:
  develop:
    build:
      useGitIgnore: true
      dockerfile: Dockerfile.develop
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION:-Debug}
    container:
      sync:
      - '**/Pages/**'
      - '**/Views/**'
      - '**/wwwroot/**'
      - '!**/*.{sln,csproj}'
      command:
      - dotnet
      - run
      - --no-restore
      - --no-build
      - --no-launch-profile
      - -c
      - ${BUILD_CONFIGURATION:-Debug}
      iterate:
        processesToKill:
        - dotnet
        - vsdbg
        buildCommands:
        - - dotnet
          - build
          - --no-restore
          - -c
          - ${BUILD_CONFIGURATION:-Debug}
