FROM node:8.12.0-alpine
ARG BUILD_CONFIGURATION=Debug
EXPOSE 3000

WORKDIR /src

COPY /Services/Tailwind.Traders.Coupon.Api/package*.json ./

COPY /Services/Tailwind.Traders.Coupon.Api/ .

COPY ["build/", "./build"]
COPY ["Services/Tailwind.Traders.Coupon.Api/package.json", "Services/Tailwind.Traders.Coupon.Api/"]
RUN npm install
COPY ["Services/Tailwind.Traders.Coupon.Api/", "Services/Tailwind.Traders.Coupon.Api/"]
ENTRYPOINT ["npm", "run", "start"]
